package lab32.lambda;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;

import java.util.*;

@DynamoDBTable(tableName = "taskmaster")
public class Task
{
    private String id;
    private String title;
    private String description;
    private String status;
    private String assignee;
    private String imageURL;

    private ArrayList<History> historyList;

    public Task() {}

    public Task(String id, String title, String description, String status, String assignee)
    {
        this.id = id;
        this.title = title;
        this.description = description;
        this.status = status;
        this.assignee = assignee;
        this.historyList = new ArrayList<>();
    }

    public Task(String id, String title, String description, String status, String assignee, String imageURL)
    {
        this.id = id;
        this.title = title;
        this.description = description;
        this.status = status;
        this.assignee = assignee;
        this.historyList = new ArrayList<>();
        this.imageURL = imageURL;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    @DynamoDBAttribute
    public ArrayList<History> getHistory() {
        return this.historyList;
    }
    public void setHistory(ArrayList<History> historyList)
    {
        this.historyList = historyList;
    }
    public void addHistory(History history)
    {
        this.historyList.add(history);
    }

    @DynamoDBAttribute
    public String getImageURL() {
        return this.imageURL;
    }
    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    @DynamoDBDocument
    public static class History
    {
        private String date;
        private String actionTaken;

        public History() {}

        public History(String date, String actionTaken)
        {
            this.date = date;
            this.actionTaken = actionTaken;
        }

        public String getDate()
        {
            return this.date;
        }

        public void setDate(String date)
        {
            this.date = date;
        }

        public String getActionTaken()
        {
            return actionTaken;
        }

        public void setActionTaken(String actionTaken)
        {
            this.actionTaken = actionTaken;
        }
    }
}
